source 'https://rubygems.org'

gem 'rake'
gem 'ruboty-replace'
gem 'ruboty-alias'
gem 'ruboty-cron'
gem 'ruboty-google_image'
gem 'ruboty-redis'
gem 'ruboty-slack_rtm'
gem 'ruboty-echo'
gem 'ruboty-lgtm'
gem 'ruboty-search_plugin'
gem 'ruboty-ruby', '>= 0.0.2'
gem 'ruboty-echo_to', '~> 1.0.1'
gem 'ruboty-hr'
gem 'ruboty-karma'

gem 'ruboty-a3rt_talk', github: 'hkdnet/ruboty-a3rt_talk'
