source 'https://rubygems.org'

ruby '2.3.0'

gem 'rake'
gem 'ruboty-replace'
gem 'ruboty-alias'
gem 'ruboty-cron'
gem 'ruboty-google_image'
gem 'ruboty-redis'
gem 'ruboty-slack'
gem 'ruboty-echo'
gem 'ruboty-lgtm'
gem 'ruboty-search_plugin'
gem 'ruboty-ruby', '>= 0.0.2'
gem 'ruboty-echo_to', '~> 1.0.1'
gem 'ruboty-hr'
gem 'ruboty-karma'

gem 'ruboty-http_sample', github: 'hkdnet/ruboty-http_sample'
